In [1]:
import math
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from keras.models import Sequential
from keras.layers import Dense, LSTM
import matplotlib.pyplot as plt

Using TensorFlow backend.
C:\Users\EL FASHKA\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\EL FASHKA\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\EL FASHKA\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\EL FASHKA\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
C:\Users\EL FASHKA\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
C:\Users\EL FASHKA\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
C:\Users\EL FASHKA\anaconda3\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\EL FASHKA\anaconda3\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\EL FASHKA\anaconda3\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\EL FASHKA\anaconda3\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
C:\Users\EL FASHKA\anaconda3\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
C:\Users\EL FASHKA\anaconda3\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])

In [2]:
bitcoin = pd.read_csv('C:/Users/EL FASHKA/Desktop/FABB/BTC-EUR.csv', index_col = 'Date', parse_dates = True )
bitcoin.head()

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2014-09-17,359.546204,361.468506,351.586884,355.957367,355.957367,16389165
2014-09-18,355.588409,355.505402,319.789459,328.539368,328.539368,26691849
2014-09-19,328.278503,330.936707,298.921021,307.761139,307.761139,29560102
2014-09-20,307.665253,329.978180,303.931244,318.758972,318.758972,28736825
2014-09-21,318.120514,321.504517,306.502197,310.632446,310.632446,20702624

In [92]:
#bitcoin['Close'].plot()
#bitcoin.drop([ 'Volume'],1, inplace=True)
bitcoin.tail()

                   Close  prediction
Date
2019-08-06  10243.875977         NaN
2019-08-07  10658.732422         NaN
2019-08-08  10697.322266         NaN
2019-08-09  10516.327148         NaN
2019-08-10  10065.183594         NaN

In [60]:
predictions_d = bitcoin['2014-09':'2015-01']
s=len(predictions_d)
s

137

In [67]:
bitcoin['prediction'] = bitcoin[['Close']].shift(-s)
bitcoin.head(7)
#bitcoin.shape

                 Close  prediction
Date
2014-09-17  355.957367  200.735825
2014-09-18  328.539368  210.115540
2014-09-19  307.761139  198.418030
2014-09-20  318.758972  200.471008
2014-09-21  310.632446  189.285950
2014-09-22  312.958771  196.348068
2014-09-23  339.189758  201.196106

In [71]:
X = np.array(bitcoin.drop(['prediction'],1))
X=X[:len(bitcoin)- s]
X

array([[ 355.957367],
       [ 328.539368],
       [ 307.761139],
       ...,
       [3560.789307],
       [3502.470703],
       [3534.563477]])

In [72]:
y = np.array(bitcoin['prediction'])
y = y[:-s]
y

array([  200.735825,   210.11554 ,   198.41803 , ..., 10697.322266,
       10516.327148, 10065.183594])

In [74]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X,y, test_size=0.2)

In [75]:
pred_d_array = np.array(bitcoin.drop(['prediction'],1))[-s:]
print(pred_d_array)

[[ 3631.979492]
 [ 3623.731201]
 [ 3652.061523]
 [ 3659.444824]
 [ 3657.865967]
 [ 3710.858154]
 [ 4354.895508]
 [ 4422.508301]
 [ 4386.38623 ]
 [ 4488.186523]
 [ 4508.803223]
 [ 4634.541016]
 [ 4699.305664]
 [ 4619.98877 ]
 [ 4722.057617]
 [ 4497.265137]
 [ 4500.679199]
 [ 4506.911621]
 [ 4571.382813]
 [ 4482.450195]
 [ 4639.527832]
 [ 4649.068359]
 [ 4715.563477]
 [ 4716.388672]
 [ 4746.688477]
 [ 4726.600586]
 [ 4795.597656]
 [ 4964.707031]
 [ 4899.657227]
 [ 4678.542969]
 [ 4732.407715]
 [ 4722.169434]
 [ 4740.140625]
 [ 4690.791992]
 [ 4771.259277]
 [ 4823.619629]
 [ 4927.245605]
 [ 5147.044434]
 [ 5203.150879]
 [ 5181.746094]
 [ 5130.174805]
 [ 5209.499023]
 [ 5342.549805]
 [ 5503.882324]
 [ 5678.451172]
 [ 6413.687988]
 [ 6205.382813]
 [ 6958.033203]
 [ 7134.912598]
 [ 7321.372559]
 [ 7057.222656]
 [ 6578.515137]
 [ 6513.402832]
 [ 7342.637695]
 [ 7142.94043 ]
 [ 7131.446777]
 [ 6884.596191]
 [ 7047.166992]
 [ 7128.090332]
 [ 7185.599121]
 [ 7737.375977]
 [ 7866.871094]
 [ 7808.071777]
 [ 7775.354004]
 [ 7473.814453]
 [ 7660.288086]
 [ 7650.920898]
 [ 7824.938965]
 [ 7299.265625]
 [ 6849.163574]
 [ 6968.260742]
 [ 6936.570313]
 [ 7095.006348]
 [ 7015.779297]
 [ 6791.208984]
 [ 7068.955566]
 [ 6997.714355]
 [ 7211.592773]
 [ 7296.713867]
 [ 7741.944824]
 [ 7870.661621]
 [ 8017.551758]
 [ 8302.839844]
 [ 8109.805176]
 [ 8253.925781]
 [ 8435.329102]
 [ 8909.28418 ]
 [ 9398.578125]
 [ 9536.269531]
 [ 9659.918945]
 [10372.481445]
 [11443.038086]
 [ 9833.768555]
 [10903.563477]
 [10509.895508]
 [ 9520.881836]
 [ 9376.392578]
 [ 9566.484375]
 [10597.433594]
 [ 9937.920898]
 [ 9772.969727]
 [ 9979.533203]
 [10198.811523]
 [10953.472656]
 [11221.008789]
 [10797.560547]
 [10096.293945]
 [10473.773438]
 [10098.285156]
 [ 9098.84668 ]
 [ 9674.610352]
 [ 8452.749023]
 [ 8633.601563]
 [ 9472.157227]
 [ 9378.670898]
 [ 9589.967773]
 [ 9448.137695]
 [ 9229.929688]
 [ 8877.623047]
 [ 8806.174805]
 [ 8892.676758]
 [ 8863.532227]
 [ 8510.954102]
 [ 8582.595703]
 [ 8542.986328]
 [ 8610.65332 ]
 [ 9109.954102]
 [ 9386.741211]
 [ 9454.787109]
 [ 9727.650391]
 [ 9875.908203]
 [10500.03125 ]
 [10243.875977]
 [10658.732422]
 [10697.322266]
 [10516.327148]
 [10065.183594]]

In [77]:
from sklearn.svm import SVR
svr_rbf = SVR(kernel = 'rbf', C= 1e3, gamma=0.00001)
svr_rbf .fit(x_train, y_train)

SVR(C=1000.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma=1e-05,
    kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [78]:
svr_rbf_confidence = svr_rbf .score(x_test, y_test)
print("svr_rbf_accuracy:", svr_rbf_confidence )

svr_rbf_accuracy: 0.8493208085838859

In [79]:
svm_pred = svr_rbf.predict(x_test)
print(svm_pred)
print()

print(y_test)

[2572.47307502  511.63011533  780.32628332 6538.48773854 3470.50922192
 9635.05123821  814.27061354 7767.42235576  842.52149006 2400.33509104
 2409.97808989  803.30402713  243.69064293  570.12974249  794.14849
 1346.95957026 2465.65172263  234.32551651  267.4948077  8010.98275092
  265.17082941 6916.30013927 5952.51321661 5639.23635809 3500.77796185
 6093.11644266  884.82849986  252.69387335  796.09042001  622.43063748
 7262.37864108  274.79136993 7932.78202737 5290.65213865  319.89409883
  247.55161302  245.53600348  947.71123816  599.83126998  266.33871807
  822.45137665 7920.10013631  565.32228233 3480.75251711 5707.49184467
 2422.53182285  243.15008205 3439.74844746 6564.95335216 5722.53248475
  408.57405837 5460.37075371  861.04317275 6099.19198883 7783.09585712
  406.83506079  244.75033544 3178.17085651  328.73688814  572.96223415
 2468.18811019 7514.68477895  796.54662982 1068.2131873  5718.33908721
 7161.74490752 1376.67001272 5749.74082662 6546.37036938 8911.4284198
  296.53202455 6523.36240164  491.76989901  247.09811593 2087.57414802
  252.91702319  848.4116104   238.84012875  250.90953892  263.58273848
 2442.71649109 2366.00589937  773.30277825  229.91532882  277.41090046
  271.14529467 3591.85710681 5489.33464177 2441.27773011 7848.73563764
 2336.44191866  801.19990573 7958.50996309 9553.79020103  796.84834
 6895.83115452 7116.61076431  574.94462374  259.90576252  254.29338869
  475.39680953 3263.40051859 7108.20868204 2421.75513027 3479.2396381
 7139.92373325 1980.22437743 6472.24601165  235.92309933 5654.27856169
  602.74767994  237.38602332  483.60878102  404.37569493 6614.35476941
  818.5880578  5371.46260875 8735.89463199  287.16474583 5683.12903046
  293.02949715 5541.34211494  556.08013433 5737.8223098  4909.71169655
 3489.7171399   343.46951792 6538.29054909 5619.05660323  848.06957914
 7946.95722082  531.5300393   330.17624164 4367.50534138 1085.92258125
  273.90211979  764.27523056 2452.55079046  431.01086526  253.29366986
 8918.66218714 9345.98891375 3631.50545537 7098.99611839  394.61683034
  230.63853419  233.74872829 3485.06930782 5603.24353924 6591.13242304
 6862.65207981  234.54162936 7639.47915424 6442.51182622  260.78989728
  522.01292876  253.47650678 4099.62508598 3469.70425331  792.01045556
 3526.32359056  255.53843421  300.84408591 7111.05977783  769.86443045
  422.78477139 6566.65098874 3534.39618991 5125.206251    787.13807772
 3560.58904131 7067.6062017   550.60256499  247.65287351 6932.39187398
 9609.66205503  549.98462158  448.66741353  543.20540998  267.35441952
 9629.61111981  229.87341453  265.61563906  567.75831695  264.70703467
  872.10226891  230.40510815 6145.8436005   311.48750657 1060.18188655
 8760.40024973 1997.32098768 3534.25453346 2954.96095958 5606.67116971
 7859.74279364  333.80038582 3568.05185458  730.12191047 8063.52720379
 2502.31764925 8064.81369522  261.55463842 1971.12816077  258.90844217
 6774.5348195   229.83229433 7599.93052105 9481.42134946  241.97763736
  426.22019082  244.13337696  252.91755171  765.34135473 2435.85635768
  449.48891908  304.58852104  496.34404784 8780.34307181  733.89376514
 7264.75576241 5412.51641407 1059.87067841  252.28711192  328.78350025
 1097.11404853  299.93953618  232.03980348  246.6150885   499.03695935
  246.30438704 5289.10094569  737.11931096 5179.73341838  277.28748579
  556.67682963 3920.40762271  253.76319039 9480.90753232 8014.90504905
 3551.37555985 5462.00777546 5743.68436817 6520.49517632 7149.90029962
 7154.32945017 5680.67114014 2480.73679073  247.71635705 4808.10852673
 5662.82668286  475.0020929  9274.89376646  312.71650024  231.00361297
  338.99177842 6448.81264735  242.10592186  265.3692221  5787.23563225
 5049.50751534 6925.66324038 5559.48553582  559.45120341 4931.42518885
 8385.27657781  261.16828493 3577.11693452  316.3990699  7252.92701303
  574.96325256 6090.50550833 4888.68263903 2433.76259818 9527.68945232
 5613.72159066  491.37400731  250.58276311 9498.78405647  456.59529788
 6370.74894523 4066.75986553 7617.91512413  988.8019159  3523.69103532
  235.80274309  844.65655889  791.24747493 2432.64730341  480.56552958
  856.51868286  858.26928089  460.38947163  383.2718025  9310.72821848
 6565.4892423   249.04600507 5666.03223776 8383.11119596 9538.97710735
  264.10325145 2433.40284024 2416.57686788  252.48390626  297.53626244
  451.74599647 3667.25319568  247.51345157  547.23432657 8564.88151384
 7270.90563625  258.31626961  244.89410068  260.9713783   890.63049691
  238.04637641 3574.22057916  732.44041988 5887.02065938  273.43976935
  570.44579846 8051.79609898  231.45875073 6324.10220011  367.09289301
  238.9432522   480.06361253  772.04911469 8425.41949055  230.96622915
  560.84820117]

[ 3451.257568   526.203674   937.124084  4740.283203  3576.835938
  5130.174805   657.297424  4354.895508   662.39856   2312.179688
  3562.424561  1111.544678   369.136383   599.009155   861.565552
  1328.717651  3854.704102   204.27301    346.401123  9674.610352
   401.89801   5074.62207   5603.438965  5549.626953  3527.745605
  6387.591797  1168.70874    204.698029   843.645508   385.963898
  6314.060059   210.811859  9381.728516  7278.083984   203.059128
   378.131744   394.602509  1006.470154   412.687256   272.494629
  1083.284424  7057.222656   391.623291  3258.58374   6657.345703
  2763.494873   313.787018  3673.137451  6536.92041   5839.276367
   670.47345   5432.755859   710.047241  6331.532715  7605.512695
   663.985291   216.241547  3398.996582   378.912994   546.893311
  3514.293945  6683.214355   985.967346  1100.518433  5389.992188
  7015.779297  1400.683228  4064.75293   5302.757324 11776.447266
   246.68457   6434.650391   518.562073   214.952301  1612.789429
   202.990082   732.417175   350.906342   219.655685   333.942261
  3674.391846  3287.669189   848.857483   302.538513   215.950684
   375.236969  3833.607666  5481.46875   3666.219482  9398.578125
  2427.029541  1059.184814  7650.095215  9054.121094   940.247192
  7410.166504 11443.038086   476.954895   212.286865   259.102478
   507.3703    3289.775146 10903.563477  3698.505859  3445.985352
  7650.920898  2249.71875  16221.844727   420.736176  5734.730957
   555.4151     402.184143   591.370972   584.305054  6139.01416
   648.647339  3217.80127   8510.954102   218.176437  6073.234375
   228.503372  4776.865234   546.738342  5762.466309  5710.907715
  3395.228027   194.238388 13862.959961  5464.854004  1090.564209
  7982.648926   544.126404   369.440887  3334.840332  1072.187866
   413.10733    977.377075  3650.117432   376.704254   211.80928
  7342.637695  4571.382813  3549.296875 10597.433594   550.729919
   304.129974   239.2005    3145.284912  5460.403809  7240.419922
  7142.606445   235.483017 13333.530273  4980.099609   332.595245
   529.02301    386.489471  3695.389893  3572.190918   859.002075
  3502.470703   338.281311   251.924515 10372.481445   916.715454
   373.079498  6605.740723  3729.454834  9550.607422   881.269348
  3537.531494  6865.993652   610.373047   348.031342  7460.788086
  8958.243164   539.881653   380.951263   614.728088   234.72496
 12237.277344   204.101883   396.360016   405.33078    349.233673
   982.049377   309.104919  5764.513672   250.388046  1105.212524
  9464.833008  2176.186523  3224.065674  3035.792725  5627.106934
  7741.944824   193.814651  3003.624023   582.33429   7331.153809
  3430.922852  8452.749023   230.43306   2210.980713   210.369736
  7269.077148   415.249268  8529.861328 10797.099609   395.608734
   616.757568   385.213684   265.963013   914.332703  3824.62793
   390.609741   372.675323   509.06308   8863.532227   585.216125
  8112.359863  3488.168213  1111.123657   243.55423    204.125992
  1135.730469   229.614639   191.402786   368.081207   529.467102
   263.743164  5558.991211   580.609497  6786.318359   382.577332
   395.465027  3416.384521   262.624298  9498.691406  9328.327148
  5072.282715  5674.999512  5322.519531  5624.187988  6578.515137
  9833.768555  3124.268555  1682.200073   202.665375  7189.393555
  5632.015137   511.084961  8806.174805   202.458817   210.808044
   227.142212  5820.34082    411.526123   396.41272   5598.709961
  3608.391357  6454.709961  7083.072266   392.624939  3289.634033
  4771.259277   278.903137  5662.807617   198.41803   7095.006348
   394.857452  5758.733887  3192.196777  3839.935791  7047.166992
  7210.70752    559.499329   217.409195 12656.952148   374.052429
  7121.830078  3215.769775  4386.38623    667.894836  3463.68042
   333.654572   691.03241    941.114258  2156.393799   364.320953
   690.950867   650.650208   539.408752   477.349976 11221.008789
  6986.245117   234.77861   6828.907715  4690.791992  6636.710449
   333.557831  2068.151855  2209.35083    362.885406   366.290771
   607.197021  3389.312256   397.086334   550.288147  9589.967773
  5181.746094   213.006149   353.431549   230.683945   972.326233
   236.694443  3223.957764   583.913574  5562.660645   232.594925
   394.401276  9536.269531   396.616608 13134.529297   363.525665
   209.777649   518.710999   955.838501  8117.646973   299.276489
   401.416809]

In [111]:
svm_pred = svr_rbf.predict(pred_d_array)
print(svm_pred)

[9658.47371253 9654.47902133 9650.08866331 9640.84589046 9643.08957108
 9497.84275706 6945.92832073 7048.16330707 6973.34905619 7278.08950908
 7366.24178892 7874.23089684 8007.68009238 7828.05493453 8024.11806615
 7316.34598462 7330.97907894 7357.98150793 7641.6113353  7254.48715983
 7888.81020119 7914.82690046 8021.0610437  8021.521469   8024.14971784
 8025.48936211 7974.54250433 7481.49108719 7712.58109618 7978.61890635
 8026.33237347 8024.15937091 8025.89222315 7997.38537113 8006.91304966
 7921.09132985 7620.19173587 6378.04515373 5829.35611539 6049.1843203
 6523.57796089 5762.17648519 4354.34311083 3507.7140192  3527.72709162
 5598.89978557 5281.46227413 5492.75264882 5558.68869586 5789.19715433
 5471.13450037 5702.0834693  5671.30390518 5792.59330704 5571.11850181
 5553.44404565 5587.1355192  5465.91186123 5548.44418246 5640.47706484
 5635.95241275 5710.52232577 5682.53096624 5661.26040557 5710.4360861
 5602.23664697 5601.05299534 5692.27614039 5779.26764471 5637.38567144
 5483.47068308 5516.22070384 5504.59664281 5460.55273272 5703.35820149
 5479.2779837  5465.04231438 5681.67808206 5777.70078403 5638.87770764
 5711.67424502 5695.55062815 5579.45243027 5657.4917743  5598.14921199
 5595.56470695 6119.32146762 6447.79436817 6570.70297922 6751.20644099
 6185.06151816 6544.38617564 6993.68195815 7001.03899245 6383.77189962
 6556.55812442 6417.29798468 6603.35956874 6612.41787554 6912.16154538
 6947.24209755 6829.16131887 6302.08236488 6933.80574388 6502.7478806
 7027.25158197 6530.91288238 6308.08732999 6525.78166326 5870.21246913
 6779.04490466 5611.50552602 5981.81538787 6517.74907096 6420.69745709
 6634.02112371 6498.4828791  6088.52815043 6173.19482826 6235.54490113
 6149.01936549 6192.88551565 5694.75867372 5852.10991038 5759.04736655
 5923.19613398 5875.48456392 6432.23660654 6504.01177592 6878.00596986
 6985.45516835 6361.68011981 6234.24311538 6781.00764602 6875.51503533
 6398.70242249 6612.60847869]

In [112]:
print(bitcoin.tail(s))

                   Close  prediction
Date
2019-03-27   3631.979492         NaN
2019-03-28   3623.731201         NaN
2019-03-29   3652.061523         NaN
2019-03-30   3659.444824         NaN
2019-03-31   3657.865967         NaN
...                  ...         ...
2019-08-06  10243.875977         NaN
2019-08-07  10658.732422         NaN
2019-08-08  10697.322266         NaN
2019-08-09  10516.327148         NaN
2019-08-10  10065.183594         NaN

[137 rows x 2 columns]

In [15]:
x_train = []
y_train = []
for i in range(60, len(train_data)):
    x_train.append(train_data[i-60:i, 0])
    y_train.append(train_data[i, 0])
    if i <= 60:
        print(x_train)
        print(y_train)
        print()

[array([0.72659129, 0.71462973, 0.68929339, 0.68707744, 0.6802035 ,
       0.67247032, 0.64942906, 0.63191634, 0.61444884, 0.60569813,
       0.59787451, 0.60079141, 0.59773884, 0.60459016, 0.60373092,
       0.60662521, 0.60775579, 0.60356133, 0.60360656, 0.61193895,
       0.62157151, 0.63226682, 0.64286037, 0.65588468, 0.66858112,
       0.68429621, 0.6988355 , 0.68627473, 0.67429056, 0.66428491,
       0.65200678, 0.        , 0.64864895, 0.        , 0.64384398,
       0.        , 0.6454381 , 0.        , 0.65187111, 0.        ,
       0.67597513, 0.        , 0.70018089, 0.        , 0.71518372,
       0.        , 0.72572075, 0.        , 0.72903335, 0.        ,
       0.72533635, 0.        , 0.7149576 , 0.        , 0.70239683,
       0.        , 0.68944036, 0.        , 0.67780667, 0.        ])]
[0.6854946297343132]